DROP TABLE IF EXISTS films, ratings, genres, users, films_genre, films_likes, users_friends;

CREATE TABLE IF NOT EXISTS ratings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    mpa varchar(32)
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name varchar(255),
    description varchar(255),
    birthday date,
    duration integer,
    mpa_id integer REFERENCES ratings(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    genre varchar(64)
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    email varchar(255),
    login varchar(255),
    name varchar(255),
    birthday date
);

CREATE TABLE IF NOT EXISTS films_genre (
    film_id integer NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    genre_id integer NOT NULL  REFERENCES genres(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS films_likes (
    film_id integer NOT NULL  REFERENCES films(id) ON DELETE CASCADE,
    user_id integer NOT NULL  REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS users_friends (
    user_id integer NOT NULL  REFERENCES users(id) ON DELETE CASCADE,
    friends_id integer NOT NULL  REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, friends_id)
);